
//THE SOURCE CODE GIVEN IN QUESTION USES A WRONG FORMAT SPECIFIER FOR 10 DIGIT LONG NUMBER
// IT SHOULD BE %lld WHICH IS USD FOR LONG LONG SIGNED INTEGER; LIKE USD IN THE CODE BELOW
// HOWEVER THE FORMAT USED IN QUESTION IS %d, which is wrong.
#include<stdio.h>
int main(){
	long long int testinteger=3000000000;
	printf("number is %lld", testinteger);
	
}
